baseurl: /blog

markdown:         rdiscount
pygments:         true
paginate:         4

title:            The One Theme
url:              http://simonmysun.github.com/blog
feed:             /atom.xml
author:
    name:         SimonMYSun
    email:        simonmysun@gmail.com
    description:  "Simon MY Sun's blog"

about:            "Learning maths, TCS, and .etc. "
follow:
    email:        simonmysun@gmail.com
    github:       https://github.com/simonmysun
    twitter:      http://www.twitter.com/simonmysun
    google:       https://plus.google.com/116961333351449443401
    facebook:     https://facebook.com/simonmysun
description:      The Blog of MY Sun 

indexContent:     true
imageLink:        http://hdn.xnimg.cn/photos/hdn521/20130620/2210/h_large_j3zZ_b2f5000005b1113e.jpg


style:            /css/style.css
blogName:         SimonMYSun 
blogDesc:         Life Journal here
favicon:          /favicon.ico
theme:            default

comments :

provider : disqus

disqus :

short_name : tiansj

disqus:           simonmysunblog   

copyright:        Copyright © 2011-2012 PIZn All rights reserved.
test:             ok
